/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/fusioninfer/fusioninfer/api/core/v1alpha1"
	applyconfigurationcorev1alpha1 "github.com/fusioninfer/fusioninfer/client-go/applyconfiguration/core/v1alpha1"
	scheme "github.com/fusioninfer/fusioninfer/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterRuntimeProfilesGetter has a method to return a ClusterRuntimeProfileInterface.
// A group's client should implement this interface.
type ClusterRuntimeProfilesGetter interface {
	ClusterRuntimeProfiles() ClusterRuntimeProfileInterface
}

// ClusterRuntimeProfileInterface has methods to work with ClusterRuntimeProfile resources.
type ClusterRuntimeProfileInterface interface {
	Create(ctx context.Context, clusterRuntimeProfile *corev1alpha1.ClusterRuntimeProfile, opts v1.CreateOptions) (*corev1alpha1.ClusterRuntimeProfile, error)
	Update(ctx context.Context, clusterRuntimeProfile *corev1alpha1.ClusterRuntimeProfile, opts v1.UpdateOptions) (*corev1alpha1.ClusterRuntimeProfile, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.ClusterRuntimeProfile, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.ClusterRuntimeProfileList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.ClusterRuntimeProfile, err error)
	Apply(ctx context.Context, clusterRuntimeProfile *applyconfigurationcorev1alpha1.ClusterRuntimeProfileApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.ClusterRuntimeProfile, err error)
	ClusterRuntimeProfileExpansion
}

// clusterRuntimeProfiles implements ClusterRuntimeProfileInterface
type clusterRuntimeProfiles struct {
	*gentype.ClientWithListAndApply[*corev1alpha1.ClusterRuntimeProfile, *corev1alpha1.ClusterRuntimeProfileList, *applyconfigurationcorev1alpha1.ClusterRuntimeProfileApplyConfiguration]
}

// newClusterRuntimeProfiles returns a ClusterRuntimeProfiles
func newClusterRuntimeProfiles(c *FusioninferV1alpha1Client) *clusterRuntimeProfiles {
	return &clusterRuntimeProfiles{
		gentype.NewClientWithListAndApply[*corev1alpha1.ClusterRuntimeProfile, *corev1alpha1.ClusterRuntimeProfileList, *applyconfigurationcorev1alpha1.ClusterRuntimeProfileApplyConfiguration](
			"clusterruntimeprofiles",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corev1alpha1.ClusterRuntimeProfile { return &corev1alpha1.ClusterRuntimeProfile{} },
			func() *corev1alpha1.ClusterRuntimeProfileList { return &corev1alpha1.ClusterRuntimeProfileList{} },
		),
	}
}
