/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/fusioninfer/fusioninfer/api/core/v1alpha1"
	applyconfigurationcorev1alpha1 "github.com/fusioninfer/fusioninfer/client-go/applyconfiguration/core/v1alpha1"
	scheme "github.com/fusioninfer/fusioninfer/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InferenceServicesGetter has a method to return a InferenceServiceInterface.
// A group's client should implement this interface.
type InferenceServicesGetter interface {
	InferenceServices(namespace string) InferenceServiceInterface
}

// InferenceServiceInterface has methods to work with InferenceService resources.
type InferenceServiceInterface interface {
	Create(ctx context.Context, inferenceService *corev1alpha1.InferenceService, opts v1.CreateOptions) (*corev1alpha1.InferenceService, error)
	Update(ctx context.Context, inferenceService *corev1alpha1.InferenceService, opts v1.UpdateOptions) (*corev1alpha1.InferenceService, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, inferenceService *corev1alpha1.InferenceService, opts v1.UpdateOptions) (*corev1alpha1.InferenceService, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.InferenceService, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.InferenceServiceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.InferenceService, err error)
	Apply(ctx context.Context, inferenceService *applyconfigurationcorev1alpha1.InferenceServiceApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.InferenceService, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, inferenceService *applyconfigurationcorev1alpha1.InferenceServiceApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.InferenceService, err error)
	InferenceServiceExpansion
}

// inferenceServices implements InferenceServiceInterface
type inferenceServices struct {
	*gentype.ClientWithListAndApply[*corev1alpha1.InferenceService, *corev1alpha1.InferenceServiceList, *applyconfigurationcorev1alpha1.InferenceServiceApplyConfiguration]
}

// newInferenceServices returns a InferenceServices
func newInferenceServices(c *FusioninferV1alpha1Client, namespace string) *inferenceServices {
	return &inferenceServices{
		gentype.NewClientWithListAndApply[*corev1alpha1.InferenceService, *corev1alpha1.InferenceServiceList, *applyconfigurationcorev1alpha1.InferenceServiceApplyConfiguration](
			"inferenceservices",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.InferenceService { return &corev1alpha1.InferenceService{} },
			func() *corev1alpha1.InferenceServiceList { return &corev1alpha1.InferenceServiceList{} },
		),
	}
}
