/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/fusioninfer/fusioninfer/api/core/v1alpha1"
	applyconfigurationcorev1alpha1 "github.com/fusioninfer/fusioninfer/client-go/applyconfiguration/core/v1alpha1"
	scheme "github.com/fusioninfer/fusioninfer/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RuntimeProfilesGetter has a method to return a RuntimeProfileInterface.
// A group's client should implement this interface.
type RuntimeProfilesGetter interface {
	RuntimeProfiles(namespace string) RuntimeProfileInterface
}

// RuntimeProfileInterface has methods to work with RuntimeProfile resources.
type RuntimeProfileInterface interface {
	Create(ctx context.Context, runtimeProfile *corev1alpha1.RuntimeProfile, opts v1.CreateOptions) (*corev1alpha1.RuntimeProfile, error)
	Update(ctx context.Context, runtimeProfile *corev1alpha1.RuntimeProfile, opts v1.UpdateOptions) (*corev1alpha1.RuntimeProfile, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.RuntimeProfile, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.RuntimeProfileList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.RuntimeProfile, err error)
	Apply(ctx context.Context, runtimeProfile *applyconfigurationcorev1alpha1.RuntimeProfileApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.RuntimeProfile, err error)
	RuntimeProfileExpansion
}

// runtimeProfiles implements RuntimeProfileInterface
type runtimeProfiles struct {
	*gentype.ClientWithListAndApply[*corev1alpha1.RuntimeProfile, *corev1alpha1.RuntimeProfileList, *applyconfigurationcorev1alpha1.RuntimeProfileApplyConfiguration]
}

// newRuntimeProfiles returns a RuntimeProfiles
func newRuntimeProfiles(c *FusioninferV1alpha1Client, namespace string) *runtimeProfiles {
	return &runtimeProfiles{
		gentype.NewClientWithListAndApply[*corev1alpha1.RuntimeProfile, *corev1alpha1.RuntimeProfileList, *applyconfigurationcorev1alpha1.RuntimeProfileApplyConfiguration](
			"runtimeprofiles",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.RuntimeProfile { return &corev1alpha1.RuntimeProfile{} },
			func() *corev1alpha1.RuntimeProfileList { return &corev1alpha1.RuntimeProfileList{} },
		),
	}
}
