/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/fusioninfer/fusioninfer/api/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ComponentStatusApplyConfiguration represents a declarative configuration of the ComponentStatus type for use
// with apply.
type ComponentStatusApplyConfiguration struct {
	DesiredReplicas *int32                       `json:"desiredReplicas,omitempty"`
	ReadyReplicas   *int32                       `json:"readyReplicas,omitempty"`
	NodesPerReplica *int32                       `json:"nodesPerReplica,omitempty"`
	TotalPods       *int32                       `json:"totalPods,omitempty"`
	ReadyPods       *int32                       `json:"readyPods,omitempty"`
	Phase           *corev1alpha1.ComponentPhase `json:"phase,omitempty"`
	LastUpdateTime  *v1.Time                     `json:"lastUpdateTime,omitempty"`
}

// ComponentStatusApplyConfiguration constructs a declarative configuration of the ComponentStatus type for use with
// apply.
func ComponentStatus() *ComponentStatusApplyConfiguration {
	return &ComponentStatusApplyConfiguration{}
}

// WithDesiredReplicas sets the DesiredReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredReplicas field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithDesiredReplicas(value int32) *ComponentStatusApplyConfiguration {
	b.DesiredReplicas = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithReadyReplicas(value int32) *ComponentStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithNodesPerReplica sets the NodesPerReplica field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodesPerReplica field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithNodesPerReplica(value int32) *ComponentStatusApplyConfiguration {
	b.NodesPerReplica = &value
	return b
}

// WithTotalPods sets the TotalPods field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TotalPods field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithTotalPods(value int32) *ComponentStatusApplyConfiguration {
	b.TotalPods = &value
	return b
}

// WithReadyPods sets the ReadyPods field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyPods field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithReadyPods(value int32) *ComponentStatusApplyConfiguration {
	b.ReadyPods = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithPhase(value corev1alpha1.ComponentPhase) *ComponentStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithLastUpdateTime sets the LastUpdateTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdateTime field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithLastUpdateTime(value v1.Time) *ComponentStatusApplyConfiguration {
	b.LastUpdateTime = &value
	return b
}
