/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// InferenceServiceStatusApplyConfiguration represents a declarative configuration of the InferenceServiceStatus type for use
// with apply.
type InferenceServiceStatusApplyConfiguration struct {
	ObservedGeneration *int64                                       `json:"observedGeneration,omitempty"`
	Conditions         []v1.ConditionApplyConfiguration             `json:"conditions,omitempty"`
	Components         map[string]ComponentStatusApplyConfiguration `json:"components,omitempty"`
}

// InferenceServiceStatusApplyConfiguration constructs a declarative configuration of the InferenceServiceStatus type for use with
// apply.
func InferenceServiceStatus() *InferenceServiceStatusApplyConfiguration {
	return &InferenceServiceStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *InferenceServiceStatusApplyConfiguration) WithObservedGeneration(value int64) *InferenceServiceStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *InferenceServiceStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *InferenceServiceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithComponents puts the entries into the Components field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Components field,
// overwriting an existing map entries in Components field with the same key.
func (b *InferenceServiceStatusApplyConfiguration) WithComponents(entries map[string]ComponentStatusApplyConfiguration) *InferenceServiceStatusApplyConfiguration {
	if b.Components == nil && len(entries) > 0 {
		b.Components = make(map[string]ComponentStatusApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.Components[k] = v
	}
	return b
}
