/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/fusioninfer/fusioninfer/api/core/v1alpha1"
)

// KVTransferSpecApplyConfiguration represents a declarative configuration of the KVTransferSpec type for use
// with apply.
//
// KVTransferSpec declares how the prefiller transfers the KV cache to the decoder.
type KVTransferSpecApplyConfiguration struct {
	// Connector is the KV connector that the inference engines of both roles are configured with.
	// The Controller derives the routing protocol and the settings it injects from it.
	Connector *corev1alpha1.KVConnector `json:"connector,omitempty"`
}

// KVTransferSpecApplyConfiguration constructs a declarative configuration of the KVTransferSpec type for use with
// apply.
func KVTransferSpec() *KVTransferSpecApplyConfiguration {
	return &KVTransferSpecApplyConfiguration{}
}

// WithConnector sets the Connector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Connector field is set to the value of the last call.
func (b *KVTransferSpecApplyConfiguration) WithConnector(value corev1alpha1.KVConnector) *KVTransferSpecApplyConfiguration {
	b.Connector = &value
	return b
}
