/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/fusioninfer/fusioninfer/api/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RoleApplyConfiguration represents a declarative configuration of the Role type for use
// with apply.
type RoleApplyConfiguration struct {
	Name                 *string                       `json:"name,omitempty"`
	ComponentType        *corev1alpha1.ComponentType   `json:"componentType,omitempty"`
	Strategy             *corev1alpha1.RoutingStrategy `json:"strategy,omitempty"`
	HTTPRoute            *runtime.RawExtension         `json:"httproute,omitempty"`
	Gateway              *runtime.RawExtension         `json:"gateway,omitempty"`
	EndpointPickerConfig *string                       `json:"endpointPickerConfig,omitempty"`
	Replicas             *int32                        `json:"replicas,omitempty"`
	Multinode            *MultinodeApplyConfiguration  `json:"multinode,omitempty"`
	Template             *runtime.RawExtension         `json:"template,omitempty"`
}

// RoleApplyConfiguration constructs a declarative configuration of the Role type for use with
// apply.
func Role() *RoleApplyConfiguration {
	return &RoleApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithName(value string) *RoleApplyConfiguration {
	b.Name = &value
	return b
}

// WithComponentType sets the ComponentType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ComponentType field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithComponentType(value corev1alpha1.ComponentType) *RoleApplyConfiguration {
	b.ComponentType = &value
	return b
}

// WithStrategy sets the Strategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Strategy field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithStrategy(value corev1alpha1.RoutingStrategy) *RoleApplyConfiguration {
	b.Strategy = &value
	return b
}

// WithHTTPRoute sets the HTTPRoute field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTPRoute field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithHTTPRoute(value runtime.RawExtension) *RoleApplyConfiguration {
	b.HTTPRoute = &value
	return b
}

// WithGateway sets the Gateway field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Gateway field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithGateway(value runtime.RawExtension) *RoleApplyConfiguration {
	b.Gateway = &value
	return b
}

// WithEndpointPickerConfig sets the EndpointPickerConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndpointPickerConfig field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithEndpointPickerConfig(value string) *RoleApplyConfiguration {
	b.EndpointPickerConfig = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithReplicas(value int32) *RoleApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithMultinode sets the Multinode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Multinode field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithMultinode(value *MultinodeApplyConfiguration) *RoleApplyConfiguration {
	b.Multinode = value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithTemplate(value runtime.RawExtension) *RoleApplyConfiguration {
	b.Template = &value
	return b
}
