/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/fusioninfer/fusioninfer/api/core/v1alpha1"
)

// RuntimeLoRASpecApplyConfiguration represents a declarative configuration of the RuntimeLoRASpec type for use
// with apply.
//
// RuntimeLoRASpec declares how a runtime loads the LoRA adapters that an InferenceDeployment binds.
// All roles of the runtime use the same loading mode.
type RuntimeLoRASpecApplyConfiguration struct {
	// LoadingMode is when the runtime loads the adapters.
	LoadingMode *corev1alpha1.LoRALoadingMode `json:"loadingMode,omitempty"`
}

// RuntimeLoRASpecApplyConfiguration constructs a declarative configuration of the RuntimeLoRASpec type for use with
// apply.
func RuntimeLoRASpec() *RuntimeLoRASpecApplyConfiguration {
	return &RuntimeLoRASpecApplyConfiguration{}
}

// WithLoadingMode sets the LoadingMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoadingMode field is set to the value of the last call.
func (b *RuntimeLoRASpecApplyConfiguration) WithLoadingMode(value corev1alpha1.LoRALoadingMode) *RuntimeLoRASpecApplyConfiguration {
	b.LoadingMode = &value
	return b
}
