/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/fusioninfer/fusioninfer/api/core/v1alpha1"
)

// RuntimeProfileSpecApplyConfiguration represents a declarative configuration of the RuntimeProfileSpec type for use
// with apply.
//
// RuntimeProfileSpec declares a reusable inference runtime: the backend, the LoRA loading
// capability, and either an aggregated role with its default Endpoint Picker or a prefiller and a
// decoder with their KV transfer. It describes one logical replica per role and neither sets replica
// counts nor references a Model.
type RuntimeProfileSpecApplyConfiguration struct {
	// Backend selects the inference engine adapter. All roles use the same backend.
	Backend *corev1alpha1.RuntimeBackend `json:"backend,omitempty"`
	// LoRA declares that the runtime can serve LoRA adapters and how it loads them.
	// When omitted, the runtime does not accept LoRA bindings.
	LoRA *RuntimeLoRASpecApplyConfiguration `json:"lora,omitempty"`
	// EndpointPicker declares the default Endpoint Picker of the InferenceDeployments that use this
	// runtime; an InferenceDeployment can override it. Only an aggregated runtime can set it.
	EndpointPicker *EndpointPickerSpecApplyConfiguration `json:"endpointPicker,omitempty"`
	// KVTransfer declares how the prefiller transfers the KV cache to the decoder. A runtime with a
	// prefiller and a decoder must set it, and an aggregated runtime cannot.
	KVTransfer *KVTransferSpecApplyConfiguration `json:"kvTransfer,omitempty"`
	// Aggregated declares the role of aggregated inference, where each replica runs both prefill and decode.
	Aggregated *RuntimeComponentSpecApplyConfiguration `json:"aggregated,omitempty"`
	// Prefiller declares the prefill role of Prefill/Decode disaggregation.
	Prefiller *RuntimeComponentSpecApplyConfiguration `json:"prefiller,omitempty"`
	// Decoder declares the decode role of Prefill/Decode disaggregation.
	Decoder *RuntimeComponentSpecApplyConfiguration `json:"decoder,omitempty"`
}

// RuntimeProfileSpecApplyConfiguration constructs a declarative configuration of the RuntimeProfileSpec type for use with
// apply.
func RuntimeProfileSpec() *RuntimeProfileSpecApplyConfiguration {
	return &RuntimeProfileSpecApplyConfiguration{}
}

// WithBackend sets the Backend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backend field is set to the value of the last call.
func (b *RuntimeProfileSpecApplyConfiguration) WithBackend(value corev1alpha1.RuntimeBackend) *RuntimeProfileSpecApplyConfiguration {
	b.Backend = &value
	return b
}

// WithLoRA sets the LoRA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoRA field is set to the value of the last call.
func (b *RuntimeProfileSpecApplyConfiguration) WithLoRA(value *RuntimeLoRASpecApplyConfiguration) *RuntimeProfileSpecApplyConfiguration {
	b.LoRA = value
	return b
}

// WithEndpointPicker sets the EndpointPicker field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndpointPicker field is set to the value of the last call.
func (b *RuntimeProfileSpecApplyConfiguration) WithEndpointPicker(value *EndpointPickerSpecApplyConfiguration) *RuntimeProfileSpecApplyConfiguration {
	b.EndpointPicker = value
	return b
}

// WithKVTransfer sets the KVTransfer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KVTransfer field is set to the value of the last call.
func (b *RuntimeProfileSpecApplyConfiguration) WithKVTransfer(value *KVTransferSpecApplyConfiguration) *RuntimeProfileSpecApplyConfiguration {
	b.KVTransfer = value
	return b
}

// WithAggregated sets the Aggregated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Aggregated field is set to the value of the last call.
func (b *RuntimeProfileSpecApplyConfiguration) WithAggregated(value *RuntimeComponentSpecApplyConfiguration) *RuntimeProfileSpecApplyConfiguration {
	b.Aggregated = value
	return b
}

// WithPrefiller sets the Prefiller field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefiller field is set to the value of the last call.
func (b *RuntimeProfileSpecApplyConfiguration) WithPrefiller(value *RuntimeComponentSpecApplyConfiguration) *RuntimeProfileSpecApplyConfiguration {
	b.Prefiller = value
	return b
}

// WithDecoder sets the Decoder field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Decoder field is set to the value of the last call.
func (b *RuntimeProfileSpecApplyConfiguration) WithDecoder(value *RuntimeComponentSpecApplyConfiguration) *RuntimeProfileSpecApplyConfiguration {
	b.Decoder = value
	return b
}
