/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// RuntimeComponentSpecApplyConfiguration represents a declarative configuration of the RuntimeComponentSpec type for use
// with apply.
//
// RuntimeComponentSpec declares one role of a runtime: the Pod template of a logical replica and,
// when the replica spans several nodes, the node count.
type RuntimeComponentSpecApplyConfiguration struct {
	// PodTemplate is the Pod template of the role.
	PodTemplate *v1.PodTemplateSpecApplyConfiguration `json:"podTemplate,omitempty"`
	// Multinode spreads each logical replica over several nodes: a leader and nodeCount - 1 workers,
	// all created from podTemplate. When omitted, each logical replica is a single Pod.
	Multinode *MultinodeSpecApplyConfiguration `json:"multinode,omitempty"`
}

// RuntimeComponentSpecApplyConfiguration constructs a declarative configuration of the RuntimeComponentSpec type for use with
// apply.
func RuntimeComponentSpec() *RuntimeComponentSpecApplyConfiguration {
	return &RuntimeComponentSpecApplyConfiguration{}
}

// WithPodTemplate sets the PodTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplate field is set to the value of the last call.
func (b *RuntimeComponentSpecApplyConfiguration) WithPodTemplate(value *v1.PodTemplateSpecApplyConfiguration) *RuntimeComponentSpecApplyConfiguration {
	b.PodTemplate = value
	return b
}

// WithMultinode sets the Multinode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Multinode field is set to the value of the last call.
func (b *RuntimeComponentSpecApplyConfiguration) WithMultinode(value *MultinodeSpecApplyConfiguration) *RuntimeComponentSpecApplyConfiguration {
	b.Multinode = value
	return b
}
