/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/fusioninfer/fusioninfer/api/core/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterModelLister helps list ClusterModels.
// All objects returned here must be treated as read-only.
type ClusterModelLister interface {
	// List lists all ClusterModels in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.ClusterModel, err error)
	// Get retrieves the ClusterModel from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha1.ClusterModel, error)
	ClusterModelListerExpansion
}

// clusterModelLister implements the ClusterModelLister interface.
type clusterModelLister struct {
	listers.ResourceIndexer[*corev1alpha1.ClusterModel]
}

// NewClusterModelLister returns a new ClusterModelLister.
func NewClusterModelLister(indexer cache.Indexer) ClusterModelLister {
	return &clusterModelLister{listers.New[*corev1alpha1.ClusterModel](indexer, corev1alpha1.Resource("clustermodel"))}
}
