/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/fusioninfer/fusioninfer/api/core/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RuntimeProfileLister helps list RuntimeProfiles.
// All objects returned here must be treated as read-only.
type RuntimeProfileLister interface {
	// List lists all RuntimeProfiles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.RuntimeProfile, err error)
	// RuntimeProfiles returns an object that can list and get RuntimeProfiles.
	RuntimeProfiles(namespace string) RuntimeProfileNamespaceLister
	RuntimeProfileListerExpansion
}

// runtimeProfileLister implements the RuntimeProfileLister interface.
type runtimeProfileLister struct {
	listers.ResourceIndexer[*corev1alpha1.RuntimeProfile]
}

// NewRuntimeProfileLister returns a new RuntimeProfileLister.
func NewRuntimeProfileLister(indexer cache.Indexer) RuntimeProfileLister {
	return &runtimeProfileLister{listers.New[*corev1alpha1.RuntimeProfile](indexer, corev1alpha1.Resource("runtimeprofile"))}
}

// RuntimeProfiles returns an object that can list and get RuntimeProfiles.
func (s *runtimeProfileLister) RuntimeProfiles(namespace string) RuntimeProfileNamespaceLister {
	return runtimeProfileNamespaceLister{listers.NewNamespaced[*corev1alpha1.RuntimeProfile](s.ResourceIndexer, namespace)}
}

// RuntimeProfileNamespaceLister helps list and get RuntimeProfiles.
// All objects returned here must be treated as read-only.
type RuntimeProfileNamespaceLister interface {
	// List lists all RuntimeProfiles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.RuntimeProfile, err error)
	// Get retrieves the RuntimeProfile from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha1.RuntimeProfile, error)
	RuntimeProfileNamespaceListerExpansion
}

// runtimeProfileNamespaceLister implements the RuntimeProfileNamespaceLister
// interface.
type runtimeProfileNamespaceLister struct {
	listers.ResourceIndexer[*corev1alpha1.RuntimeProfile]
}
