## Append samples of your project ##
resources:
- v1alpha1_inferenceservice.yaml
- v1alpha1_modelloader.yaml
- v1alpha1_model.yaml
- v1alpha1_clustermodel.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
