/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apicorev1alpha1 "github.com/fusioninfer/fusioninfer/api/core/v1alpha1"
	versioned "github.com/fusioninfer/fusioninfer/client-go/clientset/versioned"
	internalinterfaces "github.com/fusioninfer/fusioninfer/client-go/informers/externalversions/internalinterfaces"
	corev1alpha1 "github.com/fusioninfer/fusioninfer/client-go/listers/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterRuntimeProfileInformer provides access to a shared informer and lister for
// ClusterRuntimeProfiles.
type ClusterRuntimeProfileInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() corev1alpha1.ClusterRuntimeProfileLister
}

type clusterRuntimeProfileInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterRuntimeProfileInformer constructs a new informer for ClusterRuntimeProfile type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterRuntimeProfileInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterRuntimeProfileInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterRuntimeProfileInformer constructs a new informer for ClusterRuntimeProfile type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterRuntimeProfileInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FusioninferV1alpha1().ClusterRuntimeProfiles().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FusioninferV1alpha1().ClusterRuntimeProfiles().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FusioninferV1alpha1().ClusterRuntimeProfiles().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FusioninferV1alpha1().ClusterRuntimeProfiles().Watch(ctx, options)
			},
		}, client),
		&apicorev1alpha1.ClusterRuntimeProfile{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterRuntimeProfileInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterRuntimeProfileInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterRuntimeProfileInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apicorev1alpha1.ClusterRuntimeProfile{}, f.defaultInformer)
}

func (f *clusterRuntimeProfileInformer) Lister() corev1alpha1.ClusterRuntimeProfileLister {
	return corev1alpha1.NewClusterRuntimeProfileLister(f.Informer().GetIndexer())
}
